### ISSUE TITLE
Focus Group Experiment

### ISSUE THREAD

**Issue by fahadsultan** [wfoster01/csc475spotify#4]
- [x] Recruit atleast 5 subjects (students in CSC-475) 
- [x] For each subject, ask them for 5 favorite songs. Create playlist on spotify. Note down top 3 suggestions from the algorithm to be added to playlist. 
- [x] Use your own algorithm/model to make 3 suggestions. 
- [x] Ask them to score 1/10 each of your 3 recommendations and the 3 recommendations from spotify's algorithm. 
- [x] Plot the distribution of two scores for comparison.

**Comment by wfoster01** [comment]
Recruited students, asked for artists and utilized algorithm to find one song from each artists. Asked the subjects if they heard of the suggested song, artist and if they like the song. Compare results to Spotify's current algorithm.
